//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CockFighting.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public int CockId1 { get; set; }
        public Nullable<int> CockId2 { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Cock Cock { get; set; }
        public virtual Cock Cock1 { get; set; }
    }
}
