//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CockFighting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cock
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Name { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
